### ISSUE TITLE
Suggestions on Theming CMS pages

### ISSUE THREAD

**Issue by remesq** [psijkof/ModernBusiness.OC.RazorPages#15]
Just a couple of thoughts:

1. On the `/ModernBusiness.Theme/Views/Shared/NotFound.cshtml` page, consider adding

    `@{ Layout = "_Layout.cshtml" }`

   This helps avoid having to maintain the template in two separate layout files in case you make changes to one.
  EDIT: I see now this won't work because of the Breadcrumbs, **unless** you check if the model is empty by making the following change in `/ModelBusiness.Pages.Shared/Pages/Shared/BreadcrumHeader.cshtml`

        …
        <h3 class="m-subheader__title m-subheader__title--separator">
                @if (Model != null)
                {
                    @Model.DisplayText
                }
                @if (Model != null)
                {
                    @if (Model.Content != null)
                    {
                        <small>@(Model.Content?.SubtitlePart?.Subtitle.Text ?? "")</small>
                    }
                    else
                    {
                        <small>@(Model.SubTitle ?? "")</small>
                    }
                }
            </h3>
        …
    It would work then, for example, when a Not Found is thrown (not sure about other errors). Otherwise, without this change you would get a `Cannot perform runtime binding on a null reference error`.

2. Consider adding a `Content.cshtml` view to `/ModernBusiness.Theme/Views`. Any pages created in the CMS won't by themed otherwise. I just used the `Content.cshtml` file from `TheTheme` and modified it to my needs. You can then add the layout to theme it

    `@{ Layout = "../Views/Shared/_Layout.cshtml" … }`

3. Not sure how to trigger the `_error.cshtml` view in `/ModernBusiness.Pages/Pages` because I wanted to check if it, too, was being properly themed. That's not really a suggestion, just my ramblings. :) I guess maybe importing the layout in that file would work?

**Comment by psijkof** [comment]
Great suggestions @remesq.
ad. 1 I specified the layout to be used in the NotFound page and it renders fine. (Also made it simpler).

**Comment by psijkof** [comment]
ad 2. I'm happy to see how you did that. 
ad 3. It was to display errors, but then the startup should be altered too. Will see if I get this to run.
