### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by sturlath** [psijkof/ModernBusiness.OC.RazorPages#21]
Hi I cloned the code in hope that it would help me with Orchard but I get couple of build errors.

>'IOrchardDisplayHelper' does not contain a definition for 'MarkdownToHtml' and no accessible extension method 'MarkdownToHtml' accepting a first argument of type 'IOrchardDisplayHelper' could be found (are you missing a using directive or an assembly reference?)

and 

> 'ISite' does not contain a definition for 'SupportedCultures' and no accessible extension method 'SupportedCultures' accepting a first argument of type 'ISite' could be found (are you missing a using directive or an assembly reference?)

Something special I need to do to get it to build?

**Comment by psijkof** [comment]
This project needs a big update. It was build on nightly builds.
I intend to do another sample based on v1.0 once released
